dict_language = {'en': 'English',
                 'cs': 'Czech',
                 'de': 'German',
                 'es': 'Spanish',
                 'fr': 'French',
                 'it': 'Italian',
                 'nl': 'Dutch',
                 'pl': 'Polish',
                 'pt': 'Portuguese'
                 }

list_entries_synonymes_table = ['Actives Entities',
                                'Total Synonyms in Actives Entities',
                                'Actives Entities with a Synonym',
                                '% of Actives Entities with a Synonym',
                                'Median number of synonyms in Actives Entities',
                                'Maximum number of synonyms in Actives Entities',
                                'Nomenclature Terms in Actives Entities',
                                'Groups of Disorders',
                                'Total Synonyms in Groups of Disorders',
                                'Groups of Disorders with a Synonym',
                                '% of Groups of Disorders with a Synonym',
                                'Median number of synonyms in Groups of Disorders ',
                                'Maximum number of synonyms in Groups of Disorders ',
                                'Nomenclature Terms in Groups of Disorders',
                                'Disorders',
                                'Total Synonyms in Disorders',
                                'Disorders with a Synonym',
                                '% of Disorders with a Synonym',
                                'Median number of synonyms in Disorders',
                                'Maximum number of synonyms in Disorders',
                                'Nomenclature Terms in Disorders',
                                'Subtypes of Disorders',
                                'Total Synonyms in Subtypes of Disorders',
                                'Subtypes of Disorders with a Synonym',
                                '% of Subtypes of Disorders with a Synonym',
                                'Median number of synonyms in Subtypes of Disorders',
                                'Maximum number of synonyms in Subtypes of Disorders',
                                'Nomenclature Terms in Subtypes of Disorders'
                                ]
