dict_language = {'en': 'English',
                 'cs': 'Czech',
                 'de': 'German',
                 'es': 'Spanish',
                 'fr': 'French',
                 'it': 'Italian',
                 'nl': 'Dutch',
                 'pl': 'Polish',
                 'pt': 'Portuguese'
                 }


list_entries_synonymes_table = [ 'Orphanet actives entities',
                                 'Total synonyms in Orphanet actives entities',
                                 'Orphanet actives entities with a synonym',
                                 'Orphanet actives entities with any synonym',
                                 '% of Orphanet actives entities with a synonym',
                                 '% of Orphanet actives entities with any synonym',
                                 'Median number of synonyms in Orphanet actives entities',
                                 'Average number of synonyms in Orphanet actives entities',
                                 'Average number of synonyms in Orphanet actives entities with a synonym',
                                 'Maximum number of synonyms in Orphanet actives entities',
                                 'Orphanet groups of disorders',
                                 'Total synonyms in Orphanet groups of disorders',
                                 'Orphanet groups of disorders with a synonym',
                                 'Orphanet groups of disorders with any synonym',
                                 '% of Orphanet groups of disorders with a synonym',
                                 '% of Orphanet groups of disorders with any synonym',
                                 'Median number of synonyms in Orphanet groups of disorders ',
                                 'Average number of synonyms in Orphanet groups of disorders',
                                 'Average number of synonyms in Orphanet groups of disorders with a synonym',
                                 'Maximum number of synonyms in Orphanet groups of disorders ',
                                 'Orphanet disorders',
                                 'Total synonyms in Orphanet disorders',
                                 'Orphanet disorders with a synonym',
                                 'Orphanet disorders with any synonym',
                                 '% of Orphanet disorders with a synonym',
                                 '% of Orphanet disorders with any synonym',
                                 'Median number of synonyms in Orphanet disorders',
                                 'Average number of synonyms in Orphanet disorders',
                                 'Average number of synonyms in Orphanet disorders with a synonym',
                                 'Maximum number of synonyms in Orphanet disorders',
                                 'Orphanet subtypes of disorders',
                                 'Total synonyms in Orphanet subtypes of disorders',
                                 'Orphanet subtypes of disorders with a synonym',
                                 'Orphanet subtypes of disorders with any synonym',
                                 '% of Orphanet subtypes of disorders with a synonym',
                                 '% of Orphanet subtypes of disorders with any synonym',
                                 'Median number of synonyms in Orphanet subtypes of disorders',
                                 'Average number of synonyms in Orphanet subtypes of disorders',
                                 'Average number of synonyms in Orphanet subtypes of disorders with a synonym',
                                 'Maximum number of synonyms in Orphanet subtypes of disorders',
                               ]
